// Данные узлов. Схема одного узла фиксирована под формат контентщика —
// имена полей менять нельзя. Сейчас заполнены только id и name,
// остальные поля — пустые заготовки, их позже наполняет контентщик.
export const knots = [
  {
    id: 'butterfly',
    name: 'Бабочка проверка',
    aka: '',
    verified: false,
    check: '',
    steps: [],
    usage: [],
    common_mistake: '',
    quiz: [],
  },
  {
    id: 'grapevine',
    name: 'Грейпвайн',
    aka: '',
    verified: false,
    check: '',
    steps: [],
    usage: [],
    common_mistake: '',
    quiz: [],
  },
  {
    id: 'bucket',
    name: 'Ведёрный',
    aka: '',
    verified: false,
    check: '',
    steps: [],
    usage: [],
    common_mistake: '',
    quiz: [],
  },
  {
    id: 'clove-hitch',
    name: 'Стремя',
    aka: '',
    verified: false,
    check: '',
    steps: [],
    usage: [],
    common_mistake: '',
    quiz: [],
  },
  {
    id: 'bowline',
    name: 'Булинь',
    aka: '',
    verified: false,
    check: '',
    steps: [],
    usage: [],
    common_mistake: '',
    quiz: [],
  },
];
